language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  # travis_retry retries up to 3 times. Our tests fail intermitantly, so this
  # should help.
  - travis_retry cargo test --verbose --all
