language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all --all-targets
  - cargo test --verbose --all
